# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4ad749e51cf1cf43506a009eb0c76b746b5c9ce25e961845f890409ac09b2d7b9f669b695ed6bc233aac6637536e1514cff4717b846b43abe50a13756216814

test:
  secret_key_base: 887697e2a90ea99e443eee670c17eaffb921ebaa36ffff45b70ed3bbae159eff2691d3ab4db621a947ab6e4d86a97d8ecf45f903d5568ec0195542acacb5e6b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
